server:
  port: 10500

logging:
  charset:
    file: UTF-8

spring:
  application:
    name: web-ui
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: web_ui #todo создать в своей БД схему
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    #todo свои данные для подключения к БД
    url: jdbc:postgresql://localhost:5432/labdb # url для подключения к БД в формате jdbc строки
    username: labdb # логин для подключения к БД
    password: 1q2w3e # пароль для подключения к БД

    driver-class-name: org.postgresql.Driver
    tomcat:
      max-wait: 10000
      max-active: 10
      test-on-borrow: true
      max-idle: 10
    hikari:
      pool-name: WebUiPool
  liquibase:
    default-schema: web_ui
    enabled: true

app:
  baseUrl: http://localhost:10500
